import { readdirSync } from 'node:fs';
import { resolve } from 'node:path';

import { defineConfig } from '@vben/vite-config';

// 自动读取 smart-modules 目录下所有模块并创建别名
function getSmartModuleAliases() {
  const baseDir = resolve(
    import.meta.dirname,
    '../../smart-boot/smart-modules',
  );
  const dirs = readdirSync(baseDir, { withFileTypes: true });
  const aliases: Record<string, string> = {};

  for (const dir of dirs) {
    if (dir.isDirectory() && dir.name.startsWith('smart-module-')) {
      const moduleName = dir.name.replace('smart-module-', '');
      aliases[`@smart-module/${moduleName}`] = resolve(
        baseDir,
        dir.name,
        'src',
      );
    }
  }
  return aliases;
}

function SmartModulesVirtualPlugin() {
  return {
    name: 'virtual:smart-modules',
    resolveId(id) {
      if (id === 'virtual:smart-modules') return id;
      return null;
    },
    load(id) {
      if (id !== 'virtual:smart-modules') return null;

      const base = resolve(
        import.meta.dirname,
        '../../smart-boot/smart-modules',
      );
      const dirs = readdirSync(base, { withFileTypes: true })
        .filter((d) => d.isDirectory() && d.name.startsWith('smart-module-'))
        .map((d) => d.name.replace('smart-module-', ''));

      // 构造 import.meta.glob 静态语句
      const globLines = dirs
        .map(
          (name) => `import.meta.glob('@smart-module/${name}/**/*.{vue,tsx}')`,
        )
        .join(',\n  ');

      // 注意：不能加展开运算符，Object.assign 接收对象参数即可
      return `// virtual module generated by vite plugin
const SmartModulePageMap = Object.assign({}, ${globLines});

// ---- 路径修正逻辑 ----
const fixedMap = {};
for (const key in SmartModulePageMap) {
  const targetStart = key.indexOf('/smart-boot/smart-modules');
  const newKey = targetStart !== -1 ? key.substring(targetStart) : key;
  fixedMap['/' + newKey.replace(/^\\/+/, '')] = SmartModulePageMap[key];
}

export default fixedMap;
export { fixedMap as SmartModulePageMap };
`;
    },
  };
}

export default defineConfig(async () => {
  return {
    application: {},
    vite: {
      plugins: [SmartModulesVirtualPlugin()],
      resolve: {
        alias: {
          ...getSmartModuleAliases(),
        },
      },
      server: {
        proxy: {
          '/api': {
            changeOrigin: true,
            rewrite: (path) => path.replace(/^\/api/, ''),
            // mock代理目标地址
            target: 'http://localhost:8080',
            ws: true,
          },
        },
      },
    },
  };
});
