import { resolve } from 'node:path';

import fg from 'fast-glob';

function SmartModulesVirtualPlugin(
  basePath = '../../../smart-boot/smart-modules',
) {
  return {
    name: 'virtual:smart-modules',

    resolveId(id: string) {
      if (id === 'virtual:smart-modules') return id;
      return null;
    },

    load(id: string) {
      if (id !== 'virtual:smart-modules') return null;

      const base = resolve(import.meta.dirname, basePath);

      // 扫描所有 vue / tsx 文件
      const files = fg.sync('smart-module-*/src/**/*.{vue,tsx}', {
        cwd: base,
        absolute: true,
      });

      // 生成 import 语句
      const importStatements: string[] = [];
      const mapEntries: string[] = [];

      files.forEach((file, index) => {
        const varName = `m${index}`;

        // Windows 路径兼容（非常关键）
        const normalizedPath = file.replaceAll('\\', '/');

        importStatements.push(
          `const ${varName} = () => import('${normalizedPath}');`,
        );

        // 路径修正（和你原来的逻辑一致）
        const targetStart = normalizedPath.indexOf(
          '/smart-boot/smart-modules',
        );

        let key =
          targetStart === -1
            ? normalizedPath
            : normalizedPath.slice(Math.max(0, targetStart));

        key = '/' + key.replace(/^\/+/, '');

        mapEntries.push(`'${key}': ${varName}`);
      });

      return `
// virtual module generated by vite plugin (fast-glob version)

${importStatements.join('\n')}

const SmartModulePageMap = {
  ${mapEntries.join(',\n  ')}
};

export default SmartModulePageMap;
export { SmartModulePageMap };
`;
    },
  };
}

export { SmartModulesVirtualPlugin };
