import { readdirSync } from 'node:fs';
import { resolve } from 'node:path';

function SmartModulesVirtualPlugin(
  basePath = '../../../../smart-boot/smart-modules',
) {
  return {
    name: 'virtual:smart-modules',
    resolveId(id: any) {
      if (id === 'virtual:smart-modules') return id;
      return null;
    },
    load(id: any) {
      if (id !== 'virtual:smart-modules') return null;

      const base = resolve(import.meta.dirname, basePath);
      const dirs = readdirSync(base, { withFileTypes: true })
        .filter((d) => d.isDirectory() && d.name.startsWith('smart-module-'))
        .map((d) => d.name.replace('smart-module-', ''));

      // 构造 import.meta.glob 静态语句
      const globLines = dirs
        .map(
          (name) => `import.meta.glob('@smart-module/${name}/**/*.{vue,tsx}')`,
        )
        .join(',\n  ');

      // 注意：不能加展开运算符，Object.assign 接收对象参数即可
      return String.raw`// virtual module generated by vite plugin
const SmartModulePageMap = Object.assign({}, ${globLines});

// ---- 路径修正逻辑 ----
const fixedMap = {};
for (const key in SmartModulePageMap) {
  const targetStart = key.indexOf('/smart-boot/smart-modules');
  const newKey = targetStart !== -1 ? key.substring(targetStart) : key;
  fixedMap['/' + newKey.replace(/^\/+/, '')] = SmartModulePageMap[key];
}

export default fixedMap;
export { fixedMap as SmartModulePageMap };
`;
    },
  };
}

export { SmartModulesVirtualPlugin };
